### ISSUE TITLE
Consider migrating yours bash scripts to SparrowHub.

### ISSUE THREAD

**Issue by melezhik** [vrillusions/bash-scripts#3]
Hi , @vrillusions  , I have checked your repo and would suggest you to migrate your scripts to https://sparrowhub.org - a automation scripts repository. A benefits you will gain: 

* scripts could be packaged, versioned and distributed in the same way as many convention package managers do - like apt , yum , cpan,  ruby gems, etc.

* a scripts configuration is provided out of the box with some well known formats - yaml, json, Config::general , command line parameters , etc. 

* scripts documentation support - markdown , common line ( like a Linux man ) , web interface for browsering documentation, links to github source code , etc.

* scripts authority provided by account at sparrowhub , so scripts users understand clearly who is script maintainer and who address the issues to.

For example of existed scripts - take a look at http://sparrowhub.org , let me know and I help on migration process.

ps. If does not sound interesting, just close the issue.

---

Thanks . Alexey Melezhik , the author of SparrowHub.

**Comment by vrillusions** [comment]
Hi, Alexey thanks for suggestion.  sparrowhub looks interesting but this repo is more of a "place to dump scripts so they're in version control somewhere" but isn't really a true project per se.  So it doesn't really feel like it would be a good fit here.  Again thanks for the suggestion though.

**Comment by melezhik** [comment]
Sure, Todd . I see your point. If in the future you need a way to
distribute your scripts , recall a sparrowhub ))


Hi, Alexey thanks for suggestion. sparrowhub looks interesting but this

**Comment by melezhik** [comment]
And last thing , sorry to worry you ... There is latest post on using sparrow and users scripts - http://blogs.perl.org/users/melezhik/2016/10/sparrow-remote-tasks---way-to-package-your-scripts-and-configurations.html , to make this even easier I would suggest to start using sparrow with some new scripts and see the benefits :-)
